/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rama41222.storm.sensor;

import javax.swing.BorderFactory;

/**
 *
 * @author Rama41222
 */
public class Register extends javax.swing.JFrame {

    StormPiManager parent;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    //Setting up the delegate
    Register(StormPiManager parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regUsernameTxt = new javax.swing.JTextField();
        regPasswordTxt = new javax.swing.JPasswordField();
        locationTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Sensor");

        jPanel1.setBackground(new java.awt.Color(12, 35, 49));

        regUsernameTxt.setBackground(new java.awt.Color(38, 50, 56));
        regUsernameTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        regUsernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        regUsernameTxt.setText("Username");
        regUsernameTxt.setToolTipText("Sensor Name");
        regUsernameTxt.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        regUsernameTxt.setMargin(new java.awt.Insets(4, 4, 10, 4));
        regUsernameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regUsernameTxtMouseClicked(evt);
            }
        });
        regUsernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsernameTxtActionPerformed(evt);
            }
        });

        regPasswordTxt.setBackground(new java.awt.Color(38, 50, 56));
        regPasswordTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        regPasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        regPasswordTxt.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        locationTxt.setBackground(new java.awt.Color(38, 50, 56));
        locationTxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        locationTxt.setForeground(new java.awt.Color(255, 255, 255));
        locationTxt.setText("Sensor Location");
        locationTxt.setToolTipText("Sensor Location");
        locationTxt.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        locationTxt.setMargin(new java.awt.Insets(4, 4, 10, 4));
        locationTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationTxtMouseClicked(evt);
            }
        });
        locationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTxtActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(12, 35, 49));
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rama41222/storm/sensor/icons/ic_save_white_36dp_1x.png"))); // NOI18N
        registerBtn.setText("Register");
        registerBtn.setBorderPainted(false);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regPasswordTxt)
                    .addComponent(regUsernameTxt)
                    .addComponent(locationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(regUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regUsernameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regUsernameTxtMouseClicked
        regUsernameTxt.setText("");
    }//GEN-LAST:event_regUsernameTxtMouseClicked

    private void regUsernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUsernameTxtActionPerformed

    private void locationTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationTxtMouseClicked
        locationTxt.setText("");
    }//GEN-LAST:event_locationTxtMouseClicked

    private void locationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        //set the user detains in the parent calsss(StormSensor Class) to the newly registred user.
        parent.setUser(regUsernameTxt.getText(), regPasswordTxt.getPassword());
        //Registers a new sensor
        parent.registerSensor(regUsernameTxt.getText(), regPasswordTxt.getPassword(), locationTxt.getText());

        this.dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JPasswordField regPasswordTxt;
    private javax.swing.JTextField regUsernameTxt;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
